volumes:
  pg_data:
  static:
  media:
  
services:
  db:
    image: postgres:16
    env_file: .env.prod
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    image: inswty/pitalak_backend:latest
    env_file: .env.prod
    volumes:
      - static:/app/staticfiles
      - media:/app/media/
    depends_on:
      - db
      - redis
  celery_worker:
    image: inswty/pitalak_backend:latest
    env_file: .env.prod
    command: celery -A pitalak_backend worker -l info
    depends_on:
      - redis
  gateway:
    image: inswty/pitalak_gateway:latest
    env_file: .env.prod
    volumes:
      - static:/staticfiles
      - media:/media/ 
    depends_on:
      - backend
    ports:
      - 8000:80